### ISSUE TITLE
Error running example in docs

### ISSUE THREAD

**Issue by fhightower** [fhightower/ioc-finder#216]
When running `from ioc_finder import find_iocs` in our [interactive docs](https://hightower.space/ioc-finder/#overview-interactive), I'm getting this error:

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/lib/python3.9/site-packages/ioc_finder/__init__.py", line 3, in <module>
    from .ioc_finder import (
  File "/lib/python3.9/site-packages/ioc_finder/ioc_finder.py", line 12, in <module>
    from ioc_finder import ioc_grammars
  File "/lib/python3.9/site-packages/ioc_finder/ioc_grammars.py", line 4, in <module
>
    from pyparsing import (
ImportError: cannot import name 'downcaseTokens' from 'pyparsing' (/lib/python3.9/si
te-packages/pyparsing/__init__.py)
```

**Comment by fhightower** [comment]
This may require a similar fix as was done [here](https://github.com/fhightower/ioc-finder/commit/a3866e3db6230971215419ffd13de0c6b1674b97).

**Comment by Mike-CA** [comment]
For anyone who finds this running into the same error about ImportError: cannot import name 'downcaseTokens' from 'pyparsing', when running this locally try:
pip install pyparsing==2.4.2

pip will complain about a dependency conflict but it then works.

**Comment by fhightower** [comment]
Interesting, thanks for the advice! I'll give that a try.
