### ISSUE TITLE
Use concurrent.futures

### ISSUE THREAD

**Issue by fhightower** [fhightower/ioc-finder#65]
This addresses the problems in #56 and #60.

**Comment by wesinator** [comment]
@fhightower note that switching to concurrent.futures does NOT enable running `find_iocs` within a multiprocessing pool:

```python
import ioc_finder
from multiprocessing import Pool 

l = ["Scar", "Daws"]
print(ioc_finder.__version__)

with Pool(5) as p:
    print(p.map(ioc_finder.find_iocs, l))

```

```python-traceback
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/ioc_finder/ioc_finder.py", line 425, in find_iocs
    iocs['domains'] = executor.submit(parse_domain_names, text).result()
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 466, in submit
    self._start_queue_management_thread()
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 427, in _start_queue_management_thread
    self._adjust_process_count()
  File "/usr/lib/python3.6/concurrent/futures/process.py", line 446, in _adjust_process_count
    p.start()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 103, in start
    'daemonic processes are not allowed to have children'
AssertionError: daemonic processes are not allowed to have children
```

**Comment by fhightower** [comment]
Ok, interesting. But switching to concurrent.futures does allow for running `find_iocs` in nested concurrent.futures executors. So I guess users will have to use concurrent.futures. I'm not entirely sure on the difference between concurrent.futures and multiprocessing (still need to research this).
